---
title: "Título"
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Cálculo e Álgebra Linear"
booksubtitle: "Vol 1: Vetores no plano e funções de uma variáve."
bookauthors: "Kaplan, W.; Lewis, D. J."
bookaddres: "Rio de Janeiro"
bookpublisher: "Ed. Univ, de Brasilia"
bookyear: "1972"
chaptertitle: "Introdução"
chapternumber: "0"
maincolor: "5b017d"

output: 
  bookdown::pdf_document2:
    template: template.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

\section*{PROBLEMAS}

\begin{enumerate}
  \item 
  \begin{enumerate}[label=(\alph*)]
    \item Encontre um inteiro $x$ tal que $10 \sqrt{2} < x < 10\sqrt{3}$.\\
    \iniSol
      Observemos que $10\sqrt{2}$, $x$ e $10\sqrt{3}$ são números positivos. Então:
      \begin{itemize} 
      \item Pela primeira desigualdade, temos:
      \begin{align*}
      10\sqrt{2} < x &\Rightarrow
      \begin{cases}
        (10\sqrt{2})\cdot (10\sqrt{2}) < (10\sqrt{2}) \cdot x\\
        (10\sqrt{2})\cdot x < x\cdot x
      \end{cases}
      \Rightarrow
      \begin{cases}
        200 < (10\sqrt{2}) \cdot x\\
        (10\sqrt{2}) \cdot x < x^2
      \end{cases}
      \\
      &\Rightarrow 200 < x^2
      \end{align*}
      %%
      \item Pela segunda desigualdade, temos:
      \begin{align*}
        x < 10 \sqrt{3} & \Rightarrow
        \begin{cases}
          x \cdot x < (10\sqrt{3}) \cdot x \\
          (10\sqrt{3}) \cdot x < (10\sqrt{3}) \cdot (10 \sqrt{3})
        \end{cases}
        \Rightarrow
        \begin{cases}
          x^2 < (10\sqrt{3}) \cdot x\\
          (10\sqrt{3}) \cdot x < 300
        \end{cases}
        \\
        &\Rightarrow x^2 < 300
      \end{align*}
      \end{itemize}
      %%
      Combinando os resultados acima, obtemos:
      \begin{align*}
      10\sqrt{2} < x < 10\sqrt{3} \Rightarrow 200 < x^2 < 300 &\Rightarrow x^2 = `r (15:17)^2`\\
      &\Rightarrow x = `r 15:17`.
      \end{align*}
    \fimSol
    %%%%
    \item Encontre um inteiro $x$ tal que $-5\sqrt{2} < x < -3\sqrt{3}$.\\
    \iniSol
      Observememos que $-5\sqrt{2}$, $x$ e $-3\sqrt{3}$ são todos números negativos.
      \begin{itemize}
        \item Pela primeira desigualdade:
        \begin{align*}
          -5\sqrt{2} < x &\Rightarrow 
          \begin{cases}
          (-5\sqrt{2}) \cdot (-5\sqrt{2}) > (-5\sqrt{2}) \cdot x\\
          (-5\sqrt{2}) \cdot x > x^2
          \end{cases}
          \Rightarrow
          \begin{cases}
            50 > (-5\sqrt{2}) \cdot x\\
            (-5\sqrt{2}) \cdot x > x^2
          \end{cases}
          \\
          &\Rightarrow 50 > x^2
        \end{align*}
        %%
        \item Pela segunda desigualdade,
        \begin{align*}
          x < -3\sqrt{3} &\Rightarrow
          \begin{cases}
            x \cdot x > (-3\sqrt{3})\cdot x\\
            (-3\sqrt{3}) \cdot x> (-3\sqrt{3}) \cdot (-3\sqrt{3}) 
          \end{cases}
          \Rightarrow 
          \begin{cases}
            x^2 > (-3\sqrt{3}) \cdot x\\
            (-3\sqrt{3}) \cdot x > 27
          \end{cases}
          \\
          &\Rightarrow x^2 > 27
        \end{align*}
      \end{itemize}
      %%
      Combunando os resultados acima, tem-se:
      \begin{align*}
        -5\sqrt{2} < x < -3\sqrt{3} \Rightarrow 50 > x^2 > 27 & \Rightarrow x^2 = `r knitr::combine_words((-7:-6)^2, and="\\;\\text{ou}\\;")` \\&\Rightarrow
        x^2 = `r knitr::combine_words(-7:-6, before = "(", after = ")^2", and="\\;\\text{ou}\\;")  `\\
        &\Rightarrow x = `r knitr::combine_words(-7:-6, and="\\;\\text{ou}\\;")`
      \end{align*}
    \fimSol
    %%%%
    \item Encontre um número racional $x$ tal que $\sqrt{2} < x < \sqrt{3}$.\\
    \iniSol
      \begin{align*}
        \sqrt{2} < x < \sqrt{3} &\Rightarrow (\sqrt{2})^2 < x^2 < (\sqrt{3})^2 \Rightarrow 2 < x^2 < 3
      \end{align*}
      A título de exemplo, façamos:
      \begin{align*}
        \sqrt{2} < x < \sqrt{3} &\Rightarrow 2 < x^2 < 3 \Rightarrow \dfrac{200}{100} < x^2 < \dfrac{300}{100} \\
        &\Rightarrow
        x^2 = `r knitr::combine_words((15:17)^2, before="\\dfrac{", after="}{100}", and="\\;\\text{ou}\\:")` \Rightarrow x^2 = `r knitr::combine_words(15:17, before="\\left(\\dfrac{", after="}{10}\\right)^2", and="\\;\\text{ou}\\:")` \\
        &\Rightarrow x = `r knitr::combine_words(15:17, before="\\dfrac{", after="}{10}", and="\\;\\text{ou}\\:")` 
      \end{align*}
    \fimSol
    %%%%
    \item Encontre um  número racional $x$ tal que $\pi < x < \pi + 0.01$.\\
    \iniSol
      $x = 3,14$
    \fimSol
    \end{enumerate}
    %%%%
    \item Determine se $x < y$, $x = y$, ou $x < y$ para cada um dos seguintes casos:
    \begin{enumerate}[label=(\alph*)]
      \item $x=-3$, $y = -2$
      \item $x = 1$, $y = -2$
      \item $x = \sqrt{5} - \sqrt{3}$, $y = \sqrt{7} - \sqrt{2}$
      \item $x = \dfrac{1}{\sqrt{3} - \sqrt{11}}$, $y = \dfrac{1}{\sqrt{3} - \sqrt{13}}$
    \end{enumerate}
    \iniSol
    \begin{enumerate}[label=(\alph*)]
      \item $x=-3$, $y = -2$
        \begin{align*}
          x - y = -3 - (-2) = -3 + 2 = -1 < 0 \Rightarrow x < y
        \end{align*}
      %%
      \item $x = 1$, $y = -2$
      \begin{align*}
        x - y = 1 - (-2) = 1 + 2 = 3 > 0 \Rightarrow x > y
      \end{align*}
      %%
      \item $x = \sqrt{5} - \sqrt{3}$, $y = \sqrt{7} - \sqrt{2}$
      \begin{align*}
        y - x &= (\sqrt{7} - \sqrt{2}) - (\sqrt{5} - \sqrt{3}) = \sqrt{7} - \sqrt{2} - \sqrt{5} + \sqrt{3}\\
        &= \sqrt{7} - \sqrt{5} + \sqrt{3} - \sqrt{2} = (\sqrt{7} - \sqrt{5}) + (\sqrt{3} - \sqrt{2})
      \end{align*}
      Como $\sqrt{7}- \sqrt{5} > 0$ e $\sqrt{3} - \sqrt{2}> 0$, então:
      \begin{align*}
        (\sqrt{7} - \sqrt{5}) + (\sqrt{3} - \sqrt{2}) > 0 \Rightarrow y - x > 0 \Rightarrow y > x \Rightarrow x < y
      \end{align*}
      %%
      \item $x = \dfrac{1}{\sqrt{3} - \sqrt{11}}$, $y = \dfrac{1}{\sqrt{3} - \sqrt{13}}$\\
      %%
      Façamos $u = \dfrac{1}{x} = \sqrt{3} - \sqrt{11}$ e $v = \dfrac{1}{y} = \sqrt{3} - \sqrt{13}$. Então,
      \begin{align*}
        &u - v = (\sqrt{3} - \sqrt{11}) - (\sqrt{3} - \sqrt{13}) = \sqrt{3} - \sqrt{11} - \sqrt{3} + \sqrt{13}
        = \sqrt{13} - \sqrt{11} > 0\\ \Rightarrow & u > v \Rightarrow \dfrac{1}{x} > \dfrac{1}{y} \Rightarrow x < y
      \end{align*}
    \end{enumerate}
    \fimSol
    %%%%
    \item Calcule: (a) $|-3.5|$, (b) $|0,2|$, (c) $||x||$, (d) $|-|x||$, (e) $|x-y| - |y-x|$\\
    \iniSol
    \begin{enumerate}[label=(\alph*)]
      \item $|-3.5| = 3.5$
      \item $|0,2| = 0,2$
      \item $||x|| = |x|$
      \item $|-|x|| = |-1| \cdot |x| = 1 \cdot |x| = |x|$
      \item $|x-y| - |y-x| = |x-y| - |-(x-y)| = |x-y| - |-1|\cdot|x-y| = |x-y| - |x-y| = 0$
    \end{enumerate}
    \fimSol
    %%%%
    \item Mostre que $|a-b|$ pode ser interpretado como a distância entre $a$ e $b$ sobre o eixo dos números.\\
    \iniSol
      No caso em que $a = b$, $|a-b| = 0$ que é a distãncia entre $a$ e $b$.
      %%
      Caso $a > b$:
      \begin{itemize}
        \item $a > b > 0 \Rightarrow |a-b| = a-b$
        \begin{figure}[H]
          \centering
          \begin{tikzpicture}
            \draw[-latex, thick] (-5, 0) node[above] {$-$} -- (5, 0) node[above] {$+$};
            \draw[thick] (0, 5pt) node[above] {O} -- (0, 0) node[below] {$0$};
            \draw[thick] (1, 5pt) -- (1, 0) node[below] {$b$};
            \draw[thick] (4, 5pt) -- (4, 0) node[below] {$a$};
            \draw [|-|] (1, 10pt) -- (4, 10pt) node[midway, above] {$|a-b| = a-b$};
          \end{tikzpicture}
        \end{figure}
        %%
        \item $a > b = 0 \Rightarrow |a-b| = |a-0| = |a| = a$
        \begin{figure}[H]
          \centering
          \begin{tikzpicture}
            \draw[thick] (0, 5pt) -- (0, 0) node[below] {$b = 0$};
            \draw[thick] (4, 5pt) -- (4, 0) node[below] {$a$};
            \draw [|-|] (0, 25pt) -- (4, 25pt) node[midway, above] {$|a-b| = a$};
            \draw[dashed] (0,0) -- (0, 25pt);
            \draw[dashed] (4,0) -- (4, 25pt);
            \draw[-latex, thick] (-5, 0) node[above] {$-$} -- (5, 0) node[above] {$+$};
            \draw[thick] (0, 5pt) node[above, fill=white] {O} -- (0, 0);
          \end{tikzpicture}
        \end{figure}
        %%
        \item $a > 0 > b$. Façamos $b = -|b|$, em que $|b|$ é a distância entre $b$ e o zero da reta numérica. Então: $|a-b| = |a - (-|b|)| = |a + |b|| = a + |b|$
        \begin{figure}[H]
          \centering
          \begin{tikzpicture}
            \draw[thick] (-3, 5pt) -- (-3, 0) node[below] {$b$};
            \draw[thick] (4, 5pt) -- (4, 0) node[below] {$a$};
            \draw [|-|] (0, 25pt) -- (4, 25pt) node[midway, below] {$|a| = a$};
            \draw [|-|] (0, 25pt) -- (-3, 25pt) node[midway, below] {$|b|$};
            \draw[dashed] (0,0) -- (0, 25pt);
            \draw[dashed] (4,0) -- (4, 25pt);
            \draw[dashed] (-3, 0) -- (-3, 25pt);
            \draw[|-|] (-3, 35pt) -- (4, 35pt) node[midway, above] {$|a-b| = a + |b|$};
            \draw[-latex, thick] (-5, 0) node[above] {$-$} -- (5, 0) node[above] {$+$};
            \draw[thick] (0, 5pt)  node[above, fill=white] {O} -- (0, 0) node[below] {$0$};
          \end{tikzpicture}
        \end{figure}
        %%
        \item $a = 0 > b$. Então: $|a-b| = |0 - b| = |-b| = |b|$, em que $|b|$ é a distância entre $b$ e o zero da reta numérica, que neste caso, é a posição de $a$.
        \begin{figure}[H]
          \centering
          \begin{tikzpicture}
            \draw[thick] (-3, 5pt) -- (-3, 0) node[below] {$b$};
            \draw[thick] (0, 5pt) -- (0, 0) node[below] {$a=0$};
            \draw [|-|] (-3, 25pt) -- (0, 25pt) node[midway, above] {$|a-b| = |b|$};
            \draw[dashed] (-3,0) -- (-3, 25pt);
            \draw[dashed] (0,0) -- (0, 25pt);
            \draw[-latex, thick] (-5, 0) node[above] {$-$} -- (5, 0) node[above] {$+$};
            \draw[thick] (0, 5pt) node[above, fill=white] {O} -- (0, 0);
          \end{tikzpicture}
        \end{figure}
        %%
        \item $0 > a > b$. Façamos $a = -|a|$ e $b = -|b|$. Então: $|a-b| = |-|a| - (-|b|)| = |-|a| + |b|| = ||b| - |a|| = |b| - |a|$, pois $0 < |a| < |b|$.
        \begin{figure}[H]
          \centering
          \begin{tikzpicture}
            \draw (-1, 5pt) -- (-1, 0) node[below] {$a$};
            \draw [|-|] (0, 25pt) -- (-1, 25pt) node[below, midway] {$|a|$};
            \draw[dashed] (-1, 0) -- (-1, 45pt);
            \draw (-4, 5pt) -- (-4, 0) node[below] {$b$};
            \draw[|-|] (0, 35pt) -- (-4, 35pt) node[below, midway] {$|b|$};
            \draw[dashed] (-4, 0) -- (-4, 45pt);
            \draw[|-|] (-1, 45pt) -- (-4, 45pt) node[midway, above] {$|a-b| = |b|-|a|$};
            \draw[-latex, thick] (-5, 0) node[above] {$-$} -- (5, 0) node[above] {$+$};
            \draw[thick] (0, 5pt) node[above, fill=white] {O} -- (0, 0) node[below] {$0$};
          \end{tikzpicture}
        \end{figure}
      \end{itemize}
      Os casos em que $b > a$ podem ser determinados de forma análoga, bastando lembrar que $|a-b| = |-(b-a)| = |b-a|$ e repetir o aciocínio acima.
    \fimSol
    %%%%
    \item Achar $x$ em cada um dps casos: (a) $|x| = 0$, (b) $|x| = 2$, (c) $|x-1| = 2$, (d) $|x+1| = 1$.\\
    \iniSol
    \begin{enumerate}[label=(\alph*)]
      \item $|x|=0 \Rightarrow = x = 0$
      \item $|x| = 2 \Rightarrow x = -2$ ou $x = 2$.
      \item 
      \begin{align*}
        |x-1| = 2 \Rightarrow 
        \begin{cases}
          x-1 = -2\\
          x-1 = 2
        \end{cases}
        \Rightarrow
        \begin{cases}
          x = -1\\
          x = 3
        \end{cases}
      \end{align*}
    \end{enumerate}
    \fimSol
\end{enumerate}

